### ISSUE TITLE
Fritzctl does not work when installed from pip

### ISSUE THREAD

**Issue by tobyp** [not-na/fritzctl#1]
fritzctl 1.0.0a2, Python 3.7.3

There are multiple problems:
- Several imports (e.g. `session` [1]) cannot be resolved
- The simpletr64 and requests requirements are not installed as dependencies

[1]
```python console
>>> import fritzctl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.7/site-packages/fritzctl/__init__.py", line 31, in <module>
    from session import *
ModuleNotFoundError: No module named 'session'
```

**Comment by not-na** [comment]
Thank you, I will upload the new version to PyPI.

This probably happened because I did not check whether my projects worked on clean installs back when I wrote this.
